server:
  host: 0.0.0.0
  port: 8080
camera:
  shot:
    width: 1920
    height: 1080
    timeout: 5000
    bitrate: 10000000
  video:
    width: 1920
    height: 1080
    timeout: 5000
    bitrate: 10000000
